version: '3.9'

services:
  parser_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./data:/data
    networks:
      backend:


networks:
  backend:
    name: backend
    external: true
